version: '3.7'

services:
  database_trads:
    image: postgres
    container_name: database_trads
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=tradscorretora
      - POSTGRES_DB=trads
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: trads
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_trads
    depends_on:
      - database_trads

volumes:
  pgdata:
    driver: local